# Generated by Django 6.0.3 on 2026-04-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0008_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waiting_period_hours', models.IntegerField(default=48, help_text='Minimum hours required to book in advance.')),
                ('buffer_time_minutes', models.IntegerField(default=60, help_text='Buffer time between events in the same venue.')),
                ('cancellation_policy', models.CharField(choices=[('flexible', 'Flexible'), ('moderate', 'Moderate'), ('strict', 'Strict')], default='strict', help_text='Policy for event cancellations.', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
