# Generated by Django 6.0.3 on 2026-06-04 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0010_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='management_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='management_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='management_approved_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending / Awaiting Action'), ('management_approved', 'Approved by MoA Management'), ('partial_paid', 'Advance Paid'), ('paid', 'Fully Paid'), ('approved', 'VIP Approved'), ('rejected', 'Rejected (e.g. VIP Override)'), ('cancelled', 'Cancelled by User/Admin'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='trigger',
            field=models.CharField(choices=[('pending', 'Booking Received (Pending)'), ('management_approved', 'Approved by MoA Management'), ('partial_paid', 'Advance Payment Confirmed'), ('paid', 'Full Payment Confirmed'), ('approved', 'VIP Override Approved'), ('rejected', 'Booking Rejected / Overridden'), ('cancelled', 'Booking Cancelled'), ('completed', 'Event Completed'), ('reminder_24h', '24h Event Reminder'), ('reminder_48h_pay', '48h Payment Expiration'), ('last_day', 'Meeting Conclusion')], max_length=50, unique=True),
        ),
    ]
